[client]
showSidebarNavigation = false

[theme]
base="light"
primaryColor="#C4956A"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#E8E6E0"
textColor="#1A1A2E"
font="serif"

[server]
runOnSave = true